import subprocess
import urllib.parse
from datetime import date, datetime


def export_to_obsidian(week_data, today_stats_text):
    """Create a new Obsidian note with this week's NightOwl summary."""
    today    = date.today()
    now_str  = datetime.now().strftime("%-I:%M %p")

    # Build the markdown table
    table_rows = []
    for entry in week_data:
        d   = datetime.fromisoformat(entry["date"]).strftime("%a, %b %-d")
        t   = entry["latest_str"]
        raw = entry["raw_hour"]
        if raw is None:
            emoji = "✅"
        elif raw < 12 and raw >= 2:   # 2am–6am
            emoji = "💀"
        elif raw < 12 or raw >= 22:   # midnight–2am or 10pm+
            emoji = "🔴"
        else:
            emoji = "✅"
        table_rows.append(f"| {d} | {t} | {emoji} |")

    table = "\n".join(table_rows)

    content = f"""# 🦉 NightOwl Report — {today.strftime("%B %-d, %Y")}

> Auto-generated by NightOwl at {now_str}

## Today's Status

{today_stats_text}

## This Week

| Day | Stopped Working | Status |
|-----|----------------|--------|
{table}

## Legend
- ✅ Before 10 PM — responsible human
- 🔴 After 10 PM — night owl territory
- 💀 After 2 AM — goblin mode

---
#nightowl #sleep #productivity
"""

    note_path = f"NightOwl/{today.isoformat()}"
    uri = (
        "obsidian://new?"
        + urllib.parse.urlencode({"file": note_path, "content": content})
    )
    result = subprocess.run(["open", uri], capture_output=True)
    return result.returncode == 0
